### ISSUE TITLE
[feature] Add support for Conditional GET requests

### ISSUE THREAD

**Issue by le-yams** [phrase/phrase-go#7]
Hello,

The Phrase API has a very cool [conditional requests feature](https://developers.phrase.com/api/#overview--conditional-get-requests--http-caching) but this generated client does not support it.

It seems to only require the addition of the header parameters in the openapi yaml for the related requests.

For example:
```yml
  /projects/{project_id}/locales/{id}/download:
    get:
      description: Download a locale in a specific file format.
      operationId: locale/download
      parameters:
        - ...
        - description: Conditional request Last modified condition (optional)
          explode: false
          in: header
          name: If-Modified-Since
          required: false
          schema:
            type: string
          style: simple
        - description: Conditional request ETag condition (optional)
          explode: false
          in: header
          name: If-None-Match
          required: false
          schema:
            type: string
          style: simple
        - ...
```

Could you add these parameters?

Thank you in advance :)
